name: cerdik_ppb
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_spinkit: "5.1.0"
  curved_navigation_bar: ^1.0.6 #latest version
  table_calendar: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
  - img/mascot.png
  - img/roledokter.png
  - img/rolepasien.png
  - img/loadingtop.png
  - img/loadingbody1.png
  - img/loadingbody2.png